// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bilgilserakwnmiugvot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpbGdpbHNlcmFrd25taXVndm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjUxMzQsImV4cCI6MjA1ODg0MTEzNH0.wFyhEKlju8efTgOuCzF-1p5Gjc3DPzMAhwdyf5Y60sc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);